name: Windows CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 6"
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Download OpenBLAS
        shell: powershell
        run:
          # release 0.3.22 is broken, release 0.3.23 is btter but has broken .lib file
          Invoke-WebRequest -Uri "https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21-x64.zip" `
          -OutFile ./OpenBLAS.zip
      - name: Unzip OpenBLAS
        shell: powershell
        run: |
          mkdir OpenBLAS
          move OpenBLAS.zip ./OpenBLAS
          cd OpenBLAS
          7z x -y OpenBLAS.zip
          copy .\bin\libopenblas.dll ..\
          copy .\lib\libopenblas.lib (crystal env CRYSTAL_LIBRARY_PATH)
          cd ..
      - name: Install crystal land dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
